id = "azure_foundry"
name = "Azure AI Foundry"
base_url = "https://{resource_name}.services.ai.azure.com"
doc = "https://ai.azure.com/explore/models"

[env]
AZURE_FOUNDRY_RESOURCE_NAME = "Resource name"
AZURE_FOUNDRY_API_KEY = "API key"
