defmodule LLMDB.NPM.Exporter do
  @moduledoc false

  alias LLMDB.Snapshot

  @format_version 1
  @marker_filename ".llmdb-npm-export"
  @provider_filename ~r/^[a-z0-9][a-z0-9_]{0,63}$/

  @spec export!(String.t(), keyword()) :: map()
  def export!(output_dir, opts \\ []) when is_binary(output_dir) and is_list(opts) do
    source_path = Keyword.get(opts, :source, Snapshot.source_packaged_path())
    output_dir = safe_output_dir!(output_dir)

    snapshot =
      case Snapshot.read(source_path, integrity_policy: :strict) do
        {:ok, snapshot} -> snapshot
        {:error, reason} -> raise "could not read canonical snapshot: #{inspect(reason)}"
      end

    ensure_canonical_schema!(snapshot)

    providers = Map.fetch!(snapshot, "providers")
    providers_dir = Path.join(output_dir, "providers")

    prepare_output_dir!(output_dir)
    File.mkdir_p!(providers_dir)

    provider_summaries =
      providers
      |> Enum.sort_by(fn {provider_id, _provider} -> provider_id end)
      |> Map.new(fn {provider_id, provider} ->
        write_provider!(providers_dir, provider_id, provider)
        {provider_id, provider_summary(provider)}
      end)

    model_count =
      providers
      |> Map.values()
      |> Enum.map(fn provider -> provider |> Map.fetch!("models") |> map_size() end)
      |> Enum.sum()

    manifest = %{
      "format_version" => @format_version,
      "snapshot_schema_version" => Map.fetch!(snapshot, "schema_version"),
      "catalog_version" => Map.fetch!(snapshot, "version"),
      "generated_at" => Map.fetch!(snapshot, "generated_at"),
      "snapshot_id" => Map.fetch!(snapshot, "snapshot_id"),
      "provider_count" => map_size(providers),
      "model_count" => model_count,
      "providers" => provider_summaries
    }

    Snapshot.write!(Path.join(output_dir, "manifest.json"), manifest)
    verify_export!(output_dir, snapshot, manifest)

    manifest
  end

  defp write_provider!(providers_dir, provider_id, provider) do
    unless Regex.match?(@provider_filename, provider_id) do
      raise "provider ID is not safe for an NPM subpath: #{inspect(provider_id)}"
    end

    Snapshot.write!(Path.join(providers_dir, "#{provider_id}.json"), provider)
  end

  defp provider_summary(provider) do
    %{
      "id" => Map.fetch!(provider, "id"),
      "name" => Map.get(provider, "name"),
      "base_url" => Map.get(provider, "base_url"),
      "doc" => Map.get(provider, "doc"),
      "alias_of" => Map.get(provider, "alias_of"),
      "catalog_only" => Map.get(provider, "catalog_only", false),
      "model_count" => provider |> Map.fetch!("models") |> map_size()
    }
  end

  defp verify_export!(output_dir, snapshot, manifest) do
    exported_providers =
      manifest["providers"]
      |> Map.keys()
      |> Map.new(fn provider_id ->
        path = Path.join([output_dir, "providers", "#{provider_id}.json"])
        {provider_id, path |> File.read!() |> Jason.decode!()}
      end)

    reconstructed = Map.put(snapshot, "providers", exported_providers)

    unless reconstructed == snapshot do
      raise "NPM provider shards do not reconstruct the canonical snapshot"
    end

    case Snapshot.verify(reconstructed) do
      :ok ->
        :ok

      {:error, reason} ->
        raise "reconstructed NPM snapshot failed verification: #{inspect(reason)}"
    end
  end

  defp ensure_canonical_schema!(%{"schema_version" => 1}), do: :ok

  defp ensure_canonical_schema!(snapshot) do
    raise "NPM export requires canonical snapshot schema v1, got: " <>
            inspect(Map.get(snapshot, "schema_version"))
  end

  defp safe_output_dir!(output_dir) do
    expanded = Path.expand(output_dir)
    forbidden = [Path.expand("/"), Path.expand("."), System.user_home!()]

    if expanded in forbidden or Path.dirname(expanded) == expanded do
      raise ArgumentError, "unsafe NPM export directory: #{expanded}"
    end

    expanded
  end

  defp prepare_output_dir!(output_dir) do
    case File.stat(output_dir) do
      {:error, :enoent} ->
        :ok

      {:ok, %File.Stat{type: :directory}} ->
        entries = File.ls!(output_dir)
        marker_path = Path.join(output_dir, @marker_filename)

        if entries != [] and not File.regular?(marker_path) do
          raise ArgumentError,
                "refusing to replace an NPM export directory without an ownership marker: " <>
                  output_dir
        end

      {:ok, _stat} ->
        raise ArgumentError, "NPM export path is not a directory: #{output_dir}"

      {:error, reason} ->
        raise File.Error, reason: reason, action: "read NPM export directory", path: output_dir
    end

    File.rm_rf!(output_dir)
    File.mkdir_p!(output_dir)
    File.write!(Path.join(output_dir, @marker_filename), "Generated by mix llm_db.npm.export.\n")
  end
end
