import { spawnSync } from "node:child_process";
import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";

import {
  generatedDataDirectory,
  generatedLicensePath,
  generatedManifestPath,
  generatedSourceDirectory,
  packageDirectory,
  providerDeclarationsDirectory,
  repositoryDirectory,
  rootLicensePath,
} from "./paths.mjs";

const result = spawnSync(
  "mix",
  [
    "llm_db.npm.export",
    "--output",
    generatedDataDirectory,
  ],
  {
    cwd: repositoryDirectory,
    encoding: "utf8",
  },
);

if (result.status !== 0) {
  process.stderr.write(result.stderr);
  process.stdout.write(result.stdout);
  process.exit(result.status ?? 1);
}

process.stdout.write(result.stdout);

const manifestSource = await readFile(generatedManifestPath, "utf8");
const manifest = JSON.parse(manifestSource);
const providerIds = Object.keys(manifest.providers).sort();

validateManifest(manifest, providerIds);

await Promise.all([
  mkdir(generatedSourceDirectory, { recursive: true }),
  mkdir(providerDeclarationsDirectory, { recursive: true }),
  copyFile(rootLicensePath, generatedLicensePath),
]);

await Promise.all([
  writeFile(
    new URL("../src/generated/manifest.ts", import.meta.url),
    manifestModule(manifestSource, providerIds),
  ),
  writeFile(
    new URL("../src/generated/provider-loaders.ts", import.meta.url),
    loaderModule(providerIds),
  ),
  ...providerIds.map((providerId) =>
    writeFile(
      new URL(`../src/providers/${providerId}.d.ts`, import.meta.url),
      providerDeclaration(),
    ),
  ),
]);

console.log(
  `Generated TypeScript loaders for ${providerIds.length} provider shards ` +
    `in ${packageDirectory}.`,
);

function manifestModule(source, providerIds) {
  const providerUnion = providerIds.map(JSON.stringify).join(" | ");

  return `// Generated by scripts/generate.mjs. Do not edit.
import type { Manifest } from "../types.js";

export type KnownProviderId = ${providerUnion};

export const manifest = ${source.trim()} as Manifest;
`;
}

function loaderModule(providerIds) {
  const entries = providerIds
    .map(
      (providerId) =>
        `  ${JSON.stringify(providerId)}: () => ` +
        `import("../providers/${providerId}.js").then((module) => module.default),`,
    )
    .join("\n");

  return `// Generated by scripts/generate.mjs. Do not edit.
import type { ProviderLoader } from "../types.js";
import type { KnownProviderId } from "./manifest.js";

export const providerLoaders: Readonly<
  Record<KnownProviderId, ProviderLoader>
> = {
${entries}
};
`;
}

function providerDeclaration() {
  return `import type { ProviderCatalog } from "../types.js";

declare const provider: ProviderCatalog;
export default provider;
`;
}

function validateManifest(value, providerIds) {
  if (
    value === null ||
    typeof value !== "object" ||
    value.format_version !== 1 ||
    typeof value.snapshot_id !== "string" ||
    !/^[a-f0-9]{64}$/.test(value.snapshot_id)
  ) {
    throw new Error("Elixir produced an invalid NPM shard manifest.");
  }

  if (providerIds.length !== value.provider_count) {
    throw new Error("NPM shard manifest provider count is inconsistent.");
  }
}
